<a href="https://colab.research.google.com/github/cbertolasio/python-study-group/blob/master/Pythonic_thinking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pythonic Thinking

Python developers often talk about "Pythonic Thinking."  But, what does that mean?  I am reminded of this scene in "The Matrix"...

![alt text](https://docs.google.com/uc?export=download&id=1-yyLW1Z5gs_rcwUfK5WPlF0klkDdvJ9Z)
``` Morpheus: Unfortunately, no one can be told what the Matrix is. You have to see it for yourself. ```


So, get a glass of water, swallow the red pill, and ""...buckle your seatbelt, Dorothy, 'cause Kansas is going bye-bye."

## Example 1.  List expressions.

Let's say that I have a list of numbers and I want to generate a new list that has each number squared...




In [0]:
my_numbers = [0,1,2,3,4,5,6,7,8,9]


In a language like Java, or C#, if you wanted to come up with a list that included these numbers squared, you would probably use a loop and run through the list.  Python, however, has a simplier approach...


In [0]:
my_squared_numbers = [x**2 for x in my_numbers]
print(my_squared_numbers)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


Well, that is pretty cool, but what if we want a list that includes the squared numbers only if they are even.  It turns out that is pretty easy in python too...


In [0]:
my_squared_even_numbers = [x**2 for x in my_numbers if x%2==0]  # Here we consider 0 to be even.
print(my_squared_even_numbers)

[0, 4, 16, 36, 64]


Congratulations.  You have just experienced list expressions!

## Example 2.  Lambda expressions and map...

That is all pretty cool, but isn't it just syntatic sugar?

Well, maybe.  List expressions are a very powerful and very common tool used in python programming.  I think that they are sort of like a gateway drug into more pythonic thinking...  Let's go back to our list of numbers...  Let's say that we wanted a new list, and we wanted to take the sine of each number in the list.  In pseudo code, we want something like this:

$$ \vec{x} = \{0..9\} $$
$$ \vec{y} = sin(\vec{x}) $$

(btw.  Did you know that the math sin() function takes in an angle values in radians?)

From a mathematical standpoint, the above expression states that y is vector that consists of the sine of the compnents in the vector x.  A pythonic way to think about this is to do just that.  We define a function, sine, and apply it to the list...

In [0]:
import math

x = list(range(0,9))

print("x = {}".format(x))

sine = lambda theta: math.sin(theta)

y = list(map(sine, x))
print("y = {}".format(y))


x = [0, 1, 2, 3, 4, 5, 6, 7, 8]
y = [0.0, 0.8414709848078965, 0.9092974268256817, 0.1411200080598672, -0.7568024953079282, -0.9589242746631385, -0.27941549819892586, 0.6569865987187891, 0.9893582466233818]


## Example 3.  Pythonic thinking and linear algebra

Let's continue this way of thinking a bit further.

If you think back to your linear algebra days, you probably remember that a matrix is more than just a really cool movie...  It is a multi-dimensional array of numbers.  One of the benefits of Python is that it contains a number of libraries that make working with things like matricies very intuitive.  Consider the following matricies:

$$ X =
  \begin{bmatrix}
    1 & 2 & 3  \\
    4 & 5 & 6 \\
    7 & 8 & 9
  \end{bmatrix}
 $$
 
 $$ Y = \begin{bmatrix}
    1 & 1 & -1  \\
    1 & 1 & 1 \\
    -1 & 1 & 1
  \end{bmatrix}
  $$
  
  Now, consider the following equation:
  $$ Z = X \cdot Y $$
  
  where "dot" represents [matrix multiplication](https://en.wikipedia.org/wiki/Matrix_multiplication)
  
  Computing that value in languages other than python can be somewhat involved.  Here is an example of doing the matrix product in python the long hard way...
  
  

In [0]:
import numpy as np
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
Y = np.array([[1,1,-1],[1,1,1],[-1,1,1]])

Z = np.zeros(shape=(3,3))

# Note: This is NOT pythonic thinking...
for i in range(0,3):
    for j in range(0,3):
        t = 0
        for k in range(0,3):
            t += X[i][k] * Y[k][j]
        
        Z[i,j] = t
    
print("X=\n{}".format(X))
print("Y=\n{}".format(Y))
print("Z=\n{}".format(Z))

X=
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Y=
[[ 1  1 -1]
 [ 1  1  1]
 [-1  1  1]]
Z=
[[ 0.  6.  4.]
 [ 3. 15.  7.]
 [ 6. 24. 10.]]


## A more pythonic way...

In [0]:
import numpy as np

X = np.array([[1,2,3],[4,5,6],[7,8,9]])
Y = np.array([[1,1,-1],[1,1,1],[-1,1,1]])

# This IS pythonic thinking...

Z = X.dot(Y)

print("X=\n{}".format(X))
print("Y=\n{}".format(Y))
print("Z=\n{}".format(Z))

X=
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Y=
[[ 1  1 -1]
 [ 1  1  1]
 [-1  1  1]]
Z=
[[ 0  6  4]
 [ 3 15  7]
 [ 6 24 10]]


## How is that pythonic...

If you look at the above code again, note the line:

$$ Z = X.dot(Y) $$

... is very close to 

$$ Z = X \cdot Y $$

Having code that very closely represents higher, more abstract thinking is very "pythonic".


## A true sense of the power of python...

Now, let's say that you are working on a problem related to using Singular Value Decomposition (SVD) for data compression, and you need to compute the relative error of a compressed representation of a matrix...  

$$
  \dfrac{\|A - U_k \Sigma_k V_k^T\|_F}
        {\|A\|_F}
        .
$$

In that formula, we are required to compute the Frobenius norm of a matrix A.  The the Frobenius norm is defined as:

$$ ||A||_F = [ \Sigma_{ij}abs(a_{ij})^2]^{1/2}  $$

It looks hard, but with the power baked into standard python modules...





In [0]:
A = np.array([[-4, -3, -2],[-1, 0, 1], [2, 3, 4]])

A_f = np.linalg.norm(A, ord='fro')
print("The forbenius norm of A is: {}".format(A_f))

The forbenius norm of A is: 7.745966692414834


Further reading.  Check out this [article](https://arxiv.org/pdf/1211.7102.pdf) if your interested in SVD and data compression.  

Now THAT is pythonic thinking.  By knowing a little about the definition of np.linalg.norm, we can compute it a single line!

## In summary:

In this notebook, I have attempted to scratch the surface on what "Pythonic" thinking means.  It is a vague term, but one that seems to take root in developers the more python code they write.  If you are interested in reading another resource that touches on this subject [check out this python style guide](https://docs.python-guide.org/writing/style/).

In the mean time, good luck with your continued python programming journey.

I will leave you with another Matrix reference.  (I took some liberty with this..)


![alt text](https://docs.google.com/uc?export=download&id=1nDpLRD6dCqBgKhNRTQoeTGICcXTvY5iw)